# Generated by Django 2.0.5 on 2018-05-27 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0003_auto_20180527_1510'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entity',
            old_name='entity_country',
            new_name='entity_group',
        ),
    ]
